apiVersion: v1
kind: Template
labels:
  template: ssh-client-rhel
metadata:
  annotations:
    description: An SSH client for use inside OpenShift
    iconClass: icon-shadowman
    tags: ssh,rhel
  name: ssh-client-rhel
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ssh-client
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: ssh-client
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ssh-client:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: git
    strategy:
      dockerStrategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: ssh-client
  spec:
    replicas: 1
    selector:
      name: ssh-client
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ssh-client
        name: ssh-client
      spec:
        containers:
        - image: ssh-client
          name: ssh-client
          volumeMounts:
          - name: secret-volume
            mountPath: /opt/app-root/.ssh
            readOnly: true
        volumes:
        - name: secret-volume
          secret:
            secretName: ssh-secret
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ssh-client
        from:
          kind: ImageStreamTag
          name: ssh-client:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/kevensen/openshift-ssh-client.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: "master"
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: rhel
